config/routes.rb
Rails.application.routes.draw do


  # Routes for the common pages and users:

  root to: 'common_pages#main'

  get '/dashboard', to: 'common_pages#dashboard'

  devise_for :users, path: 'users', controllers: {
    confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks',
  }

  devise_for :admins, path: 'admins', controllers: {
    confirmations: 'admins/confirmations',
    # omniauth_callbacks: 'admins/omniauth_callbacks',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    unlocks: 'admins/unlocks',
  }

  # Since the registrations module is disabled for admins, we need this workaround to enable the stock devise edit password form.
  # Why is editing your password is tied to being able to sign up for an account? Because the devise crew has drunk the RESTful kool-aid and stuck two unrelated processes on the same resource!
  # See: https://github.com/plataformatec/devise/wiki/How-To%3a-Allow-users-to-edit-their-password#solution-2

  as :admin do
    get 'admin/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
    patch 'admins' => 'admins/registrations#update', :as => 'admin_registration'
  end



  resource :user, only: [:show, :edit, :update] do
    post 'activate_second_shift'
    post 'activate_mentor_match'
    get 'unsubscribe'

    post 'set_email_subscription'
  end



  # Routes for Second Shift:

  scope 'second-shift' do
    resources :service_postings, path: 'postings', except: [:index, :destroy] do
      collection do
        get 'mine'
        get 'available'
        get 'wanted'
      end
      member do
        post 'open'
        post 'close'
      end
    end
    resources :connection_requests, 
      only: [:index, :create],
      controller: 'second_shift_connection_requests',
      as: 'ss_connection_requests' do
        member do
          post 'initiator_withdraw'
          post 'receiver_accept'
          post 'receiver_decline'
        end
      end
  end


  # Routes for Mentor Match:
  
  scope 'mentor-match' do
    resource :my_mentor_match_profile, only: [:show, :edit, :update] do
      collection do
        get 'edit_cv'
        post 'update_cv'
      end
    end
    resources :mentor_match_profiles, only: [:index, :show] do
      collection do
        post 'query'
      end
      member do
        get 'cv'
      end
    end
    resources :connection_requests,
      only: [:index, :create],
      controller: 'mentor_match_connection_requests',
      as: 'mm_connection_requests' do
        member do
          post 'initiator_withdraw'
          post 'initiator_undo_withdraw'
          post 'receiver_accept'
          post 'receiver_decline'
        end
      end
  end


  scope 'trusted-vendors' do
    resources :vendor_reviews, path: 'reviews' do
      collection do
        get 'mine'
        get 'search'
        post 'query'
      end
      member do
        post 'like'
        post 'unlike'
        post 'neutral_helpfulness'
      end
    end
  end

  scope 'cv-catalogue' do
    resource :my_cv, only: [:edit] do
      post 'update_cv'
      post 'update_cv_email'
      post 'resend_cv_email'
    end

    resources :cvs, only: [:index, :show] do
      collection do
        post 'query'
      end
    end

  end

  scope 'administration' do
    get '/dashboard', to: 'admin_pages#dashboard', as: 'admin_dashboard'

    resources :users, controller: 'admin_users', as: 'admin_users', only: [:new, :create] do

      collection do
        get 'approve_index'
        get 'disable_index'
      end

      post 'approve'
      post 'disable'
      post 'reenable'
    end

    resources :cvs, controller: 'admin_cvs', as: 'admin_cvs', only: [:index, :edit, :update]

    resources :bulk_update_record, controller: 'admin_bulk_update_record', as: 'bulk_cv', only: [:index, :new, :create, :show] do
      member do
        post :retry
      end
    end

  end


end

app/views/shared/_admins_navbar.html.slim
.hacquity-nav-list

  a href = new_admin_user_path
    .nav-link class = new_create_nav_link_class('admin_users')
      span Invite New User

  a href = approve_index_admin_users_path
    .nav-link class = nav_link_class('admin_users', 'approve_index')
      span = "Approve Users (#{User.where('admin_approved is NULL').count})"

  a href = disable_index_admin_users_path
    .nav-link class = nav_link_class('admin_users', 'disable_index')
      span Disable / Re-enable Users

  a href = admin_cvs_path
    .nav-link class = nav_link_class('admin_cvs', 'index')
      span Update User CV

  a href = new_bulk_cv_path
    .nav-link class = nav_link_class('admin_bulk_update_record', 'new')
      span New Bulk Update CV Job

  a href = bulk_cv_index_path
    .nav-link class = nav_link_class('admin_bulk_update_record', 'index')
      span View Bulk Update CV Jobs

app/views/shared/_auth_links.html.slim
/ NB: unused for the moment.

/ .dashboard-colours
/   - if user_signed_in?
/     = form_with url: destroy_user_session_path, method: :delete, local: true do |form|
/       = form.submit "Logout", class: 'mui-btn mui--color-blue-grey-600 mui--bg-color-white'
/   - else
/     = link_to "Log in", new_user_session_path, class: 'mui-btn'
/     = link_to "Sign up", new_user_registration_path, class: 'mui-btn'
/     br


/ - if devise_mapping.registerable? && controller_name != 'registrations'
/   = link_to "Sign up", new_registration_path(resource_name)
/   br


/ - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
/   = link_to "Forgot your password?", new_password_path(resource_name)
/   br


/ - if devise_mapping.confirmable? && controller_name != 'confirmations'
/   = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
/   br

app/views/shared/_cv_catalogue_navbar.html.slim
.hacquity-nav-list

  a href = cvs_path
    .nav-link class = nav_link_class('cvs', 'index')
      span Search CVs

  a href = edit_my_cv_path
    .nav-link class = edit_create_nav_link_class('my_cvs')
      span My CV

app/views/shared/_cv_email_update_button.html.slim
h3 Update CV by Email
p You can update your CV by sending it as an email attachment. Click below to send update by email instructions to get started.
= form_with url: resend_cv_email_my_cv_path, class: 'mui-form' do |form|
  = form.submit "Send Instructions", class: "mui-btn inline"

app/views/shared/_cv_form.html.slim
h2 Upload CV

= form_with url: update_path, multipart: true, local: true do |form|

  .form-section
    = form.file_field 'CV', accept: '.doc,.docx,.pdf,.txt'

  .actions
    = form.submit "Upload", class: "mui-btn"

app/views/shared/_cv_personal_information_warning.html.slim
- if not user.mentor_match_profile.personal_information.blank?
  h3 CV Personal Information
  p
    em An automated scan of your CV found some personal information that may correspond to an email address, phone number, or street address. This info is visible to any who view your CV on DoM Citizen. You may wish to upload a CV that omits this information. If the scan is in error, you may ignore this notice.

  .indent = simple_format user.mentor_match_profile.personal_information

app/views/shared/_mentor_match_navbar.html.slim
.hacquity-nav-list


  a href = my_mentor_match_profile_path
    .nav-link class = nav_link_class('my_mentor_match_profiles', 'show')
      span My Mentor Match Profile

  / a href = search_mentor_match_profiles_path
  /   .nav-link class = nav_link_class('mentor_match_profiles', 'search')
  /     span Search Profiles

  a href = mentor_match_profiles_path
    .nav-link class = nav_link_class('mentor_match_profiles', 'index')
      span Search Profiles

  a href = mm_connection_requests_path
    .nav-link class = nav_link_class('mentor_match_connection_requests', 'index')
      span
        | Connection Requests
        - if current_user.active_connection_request_count > 0
          = " (#{current_user.active_connection_request_count})"

app/views/shared/_second_shift_navbar.html.slim
.hacquity-nav-list

  a href = mine_service_postings_path 
    .nav-link class = nav_link_class('service_postings', 'mine')
      span My Postings

  a href = new_service_posting_path
    .nav-link class = new_create_nav_link_class('service_postings')
      span Create Posting

  a href = available_service_postings_path
    .nav-link class = nav_link_class('service_postings', 'available')
      span Browse Available Postings

  a href = wanted_service_postings_path
    .nav-link class = nav_link_class('service_postings', 'wanted')
      span Browse Wanted Postings

  / a href = search_service_postings_path
  /.nav-link class = nav_link_class('service_postings', 'search')
  /     span Search Postings

  a href = ss_connection_requests_path
    .nav-link class = nav_link_class('second_shift_connection_requests', 'index')
      span
        | Connection Requests
        - if current_user.active_connection_request_count > 0
          = " (#{current_user.active_connection_request_count})"

app/views/shared/_trusted_vendors_navbar.html.slim
.hacquity-nav-list

  a href = mine_vendor_reviews_path
    .nav-link class = nav_link_class('vendor_reviews', 'mine')
      span My Reviews

  a href = new_vendor_review_path
    .nav-link class = new_create_nav_link_class('vendor_reviews')
      span New Review

  a href = search_vendor_reviews_path
    .nav-link class = nav_link_class('vendor_reviews', 'search')
      span Search Reviews

  a href = vendor_reviews_path
    .nav-link class = nav_link_class('vendor_reviews', 'index')
      span Browse Reviews

app/views/shared/_user_settings_navbar.html.slim
.hacquity-nav-list

  a href = user_path
    .nav-link class = nav_link_class('users', 'show')
      span My Info

  a href = edit_user_path
    .nav-link class = edit_create_nav_link_class('users')
      span Update Info

  a href = edit_user_registration_path
    .nav-link class = edit_create_nav_link_class('registrations')
      span Update Password