config/routes.rb
Rails.application.routes.draw do


  # Routes for the common pages and users:

  root to: 'common_pages#main'

  get '/dashboard', to: 'common_pages#dashboard'

  devise_for :users, path: 'users', controllers: {
    confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks',
  }

  devise_for :admins, path: 'admins', controllers: {
    confirmations: 'admins/confirmations',
    # omniauth_callbacks: 'admins/omniauth_callbacks',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    unlocks: 'admins/unlocks',
  }

  # Since the registrations module is disabled for admins, we need this workaround to enable the stock devise edit password form.
  # Why is editing your password is tied to being able to sign up for an account? Because the devise crew has drunk the RESTful kool-aid and stuck two unrelated processes on the same resource!
  # See: https://github.com/plataformatec/devise/wiki/How-To%3a-Allow-users-to-edit-their-password#solution-2

  as :admin do
    get 'admin/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
    patch 'admins' => 'admins/registrations#update', :as => 'admin_registration'
  end



  resource :user, only: [:show, :edit, :update] do
    post 'activate_second_shift'
    post 'activate_mentor_match'
    get 'unsubscribe'

    post 'set_email_subscription'
  end



  # Routes for Second Shift:

  scope 'second-shift' do
    resources :service_postings, path: 'postings', except: [:index, :destroy] do
      collection do
        get 'mine'
        get 'available'
        get 'wanted'
      end
      member do
        post 'open'
        post 'close'
      end
    end
    resources :connection_requests, 
      only: [:index, :create],
      controller: 'second_shift_connection_requests',
      as: 'ss_connection_requests' do
        member do
          post 'initiator_withdraw'
          post 'receiver_accept'
          post 'receiver_decline'
        end
      end
  end


  # Routes for Mentor Match:
  
  scope 'mentor-match' do
    resource :my_mentor_match_profile, only: [:show, :edit, :update] do
      collection do
        get 'edit_cv'
        post 'update_cv'
      end
    end
    resources :mentor_match_profiles, only: [:index, :show] do
      collection do
        post 'query'
      end
      member do
        get 'cv'
      end
    end
    resources :connection_requests,
      only: [:index, :create],
      controller: 'mentor_match_connection_requests',
      as: 'mm_connection_requests' do
        member do
          post 'initiator_withdraw'
          post 'initiator_undo_withdraw'
          post 'receiver_accept'
          post 'receiver_decline'
        end
      end
  end


  scope 'trusted-vendors' do
    resources :vendor_reviews, path: 'reviews' do
      collection do
        get 'mine'
        get 'search'
        post 'query'
      end
      member do
        post 'like'
        post 'unlike'
        post 'neutral_helpfulness'
      end
    end
  end

  scope 'cv-catalogue' do
    resource :my_cv, only: [:edit] do
      post 'update_cv'
      post 'update_cv_email'
      post 'resend_cv_email'
    end

    resources :cvs, only: [:index, :show] do
      collection do
        post 'query'
      end
    end

  end

  scope 'administration' do
    get '/dashboard', to: 'admin_pages#dashboard', as: 'admin_dashboard'

    resources :users, controller: 'admin_users', as: 'admin_users', only: [:new, :create] do

      collection do
        get 'approve_index'
        get 'disable_index'
      end

      post 'approve'
      post 'disable'
      post 'reenable'
    end

    resources :cvs, controller: 'admin_cvs', as: 'admin_cvs', only: [:index, :edit, :update]

    resources :bulk_update_record, controller: 'admin_bulk_update_record', as: 'bulk_cv', only: [:index, :new, :create, :show] do
      member do
        post :retry
      end
    end

  end


end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  # That is, the controller that admins will use to manage ordinary users

  before_action :require_admin_login

  layout 'admin_pages'

  def new
    @user = User.new
  end

  def create

    @user = User.new user_params

    # Initialize the user's password to something unguessable
    @user.password = SecureRandom.urlsafe_base64(16)
    # Since this user was invited by an admin, we consider them approved.
    @user.admin_approved = DateTime.now
    # Similarly, since this is not someone on the internet claiming they have an email address, but an admin offering access to an email address, no sense in making the user confirm ownership.
    @user.confirmed_at = DateTime.now

    if @user.save
      redirect_to new_admin_user_path, notice: "User #{@user.name} <#{@user.email}> was invited."
      # TODO: yes, we're calling a protected devise method here. It seems to work fine but this is not ideal.
      raw_token = @user.send :set_reset_password_token
      InvitedUserPasswordChangeJob.new(@user, raw_token).deliver
      @user.send_cv_submission_mail
    else
      render :new
    end

  end

  def approve_index
    # Include recently approved users so that items do not disappear from the list in the middle of use.
    # We're going to use little inline forms which cause a turbolinks page refresh, this combined with a stable list of users gives the impression of using a single page application with no client side code :3
    @users = User.where('admin_approved is NULL or admin_approved > :three_days_ago', three_days_ago: 3.days.ago)
      .order(created_at: :desc)
      .page(params[:page])
  end

  def approve
    user = User.find params[:admin_user_id]

    user.admin_approved = DateTime.now
    user.save!
    redirect_to approve_index_admin_users_path(page: params[:page])

    NotifyUserAccountApprovedJob.new(user).deliver
  end

  def disable_index
    # TODO: would be a nicer UX to be able to search for users, but there won't be that many to start, and browsers have ctrl+f
    # 102, because users are displayed 3 per row, and this gives us a clean last row :3
    @users = User.order(name: :asc).page(params[:page]).per(102)
  end

  def disable
    user = User.find params[:admin_user_id]
    user.admin_disabled = DateTime.now
    user.save!
    redirect_to disable_index_admin_users_path(page: params[:page])
  end

  def reenable
    user = User.find params[:admin_user_id]
    user.admin_disabled = nil
    user.save!
    redirect_to disable_index_admin_users_path(page: params[:page])
  end


  protected


  def user_params
    params.require(:user).permit([:name, :email])
  end

end

app/views/admin_users/approve_index.html.slim
.mui-container

  h2 Approve Users

  p 
    em Ensure that users requesting access to DoM Citizen have a valid institutional email address before approving.

  - @users.each_slice 3 do |users_slice|
    .mui-row
      - users_slice.each do |user|
        .mui-col-md-4.mui-col-xs.12
          h3.bottom-border = user.name
          p = user.email
          - if user.admin_approved
            p = "Approved on #{user.admin_approved.strftime '%A %B %d, %Y'}"
          - else
            = form_with url: admin_user_approve_path(user), class: 'inline' do |form|
              = form.hidden_field 'page', value: params[:page]
              = form.submit 'Approve', class: "mui-btn preserve-scroll-position"



  .form-section
    - if @users.any?
      = paginate @users
    - if @users.empty?
      p 
        em No users need to be approved.

app/views/admin_users/disable_index.html.slim
.mui-container

  h2 Disable Users

  p 
    em Disabled users can't log in. Users may be disabled and re-enabled any number of times.

  - @users.each_slice 3 do |users_slice|
    .mui-row
      - users_slice.each do |user|
        .mui-col-md-4.mui-col-xs.12
          h3.bottom-border = user.name
          p = user.email
          - if user.admin_disabled
            p = "Disabled on #{user.admin_disabled.strftime '%A %B %d, %Y'}"
            = form_with url: admin_user_reenable_path(user), class: 'inline' do |form|
              = form.hidden_field 'page', value: params[:page]
              = form.submit 'Re-enable', class: "mui-btn preserve-scroll-position mui--bg-color-white mui--color-deep-purple-600"
          - else
            p
              strong Active
            = form_with url: admin_user_disable_path(user), class: 'inline' do |form|
              = form.hidden_field 'page', value: params[:page]
              = form.submit 'Disable', class: "mui-btn preserve-scroll-position"



  .form-section
    - if @users.any?
      = paginate @users
    - if @users.empty?
      p 
        em No users found.

app/views/admin_users/new.html.slim
h2 Invite User

p
  em The user will be sent an email welcoming them to DoM Citizen, and asking them to set their password.

br

= form_with model: @user, url: admin_users_path, class: 'mui-form', local: true do |f|

  - if @user.errors.any?
    #error-explanation
      h3 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being invited:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message
    br

  .mui-row
    .mui-col-md-6.mui-col-xs.12
      .field.mui-textfield
        = f.label :name
        = f.text_field :name
    .mui-col-md-6.mui-col-xs.12
      .field.mui-textfield
        = f.label :email
        = f.text_field :email


  .actions
    = f.submit "Invite User", class: 'mui-btn'