config/routes.rb
Rails.application.routes.draw do


  # Routes for the common pages and users:

  root to: 'common_pages#main'

  get '/dashboard', to: 'common_pages#dashboard'

  devise_for :users, path: 'users', controllers: {
    confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks',
  }

  devise_for :admins, path: 'admins', controllers: {
    confirmations: 'admins/confirmations',
    # omniauth_callbacks: 'admins/omniauth_callbacks',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    unlocks: 'admins/unlocks',
  }

  # Since the registrations module is disabled for admins, we need this workaround to enable the stock devise edit password form.
  # Why is editing your password is tied to being able to sign up for an account? Because the devise crew has drunk the RESTful kool-aid and stuck two unrelated processes on the same resource!
  # See: https://github.com/plataformatec/devise/wiki/How-To%3a-Allow-users-to-edit-their-password#solution-2

  as :admin do
    get 'admin/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
    patch 'admins' => 'admins/registrations#update', :as => 'admin_registration'
  end



  resource :user, only: [:show, :edit, :update] do
    post 'activate_second_shift'
    post 'activate_mentor_match'
    get 'unsubscribe'

    post 'set_email_subscription'
  end



  # Routes for Second Shift:

  scope 'second-shift' do
    resources :service_postings, path: 'postings', except: [:index, :destroy] do
      collection do
        get 'mine'
        get 'available'
        get 'wanted'
      end
      member do
        post 'open'
        post 'close'
      end
    end
    resources :connection_requests, 
      only: [:index, :create],
      controller: 'second_shift_connection_requests',
      as: 'ss_connection_requests' do
        member do
          post 'initiator_withdraw'
          post 'receiver_accept'
          post 'receiver_decline'
        end
      end
  end


  # Routes for Mentor Match:
  
  scope 'mentor-match' do
    resource :my_mentor_match_profile, only: [:show, :edit, :update] do
      collection do
        get 'edit_cv'
        post 'update_cv'
      end
    end
    resources :mentor_match_profiles, only: [:index, :show] do
      collection do
        post 'query'
      end
      member do
        get 'cv'
      end
    end
    resources :connection_requests,
      only: [:index, :create],
      controller: 'mentor_match_connection_requests',
      as: 'mm_connection_requests' do
        member do
          post 'initiator_withdraw'
          post 'initiator_undo_withdraw'
          post 'receiver_accept'
          post 'receiver_decline'
        end
      end
  end


  scope 'trusted-vendors' do
    resources :vendor_reviews, path: 'reviews' do
      collection do
        get 'mine'
        get 'search'
        post 'query'
      end
      member do
        post 'like'
        post 'unlike'
        post 'neutral_helpfulness'
      end
    end
  end

  scope 'cv-catalogue' do
    resource :my_cv, only: [:edit] do
      post 'update_cv'
      post 'update_cv_email'
      post 'resend_cv_email'
    end

    resources :cvs, only: [:index, :show] do
      collection do
        post 'query'
      end
    end

  end

  scope 'administration' do
    get '/dashboard', to: 'admin_pages#dashboard', as: 'admin_dashboard'

    resources :users, controller: 'admin_users', as: 'admin_users', only: [:new, :create] do

      collection do
        get 'approve_index'
        get 'disable_index'
      end

      post 'approve'
      post 'disable'
      post 'reenable'
    end

    resources :cvs, controller: 'admin_cvs', as: 'admin_cvs', only: [:index, :edit, :update]

    resources :bulk_update_record, controller: 'admin_bulk_update_record', as: 'bulk_cv', only: [:index, :new, :create, :show] do
      member do
        post :retry
      end
    end

  end


end

app/models/service_posting.rb
class ServicePosting < ApplicationRecord

  ServicePosting::ServiceTypes = [
    'Nanny',
    'Meal Preparation',
    'Housekeeping',
    'Driving',
    'Childcare',
    'Eldercare',
    'Errands',
    'Other'
  ]

  belongs_to :user

  has_many :initiator_connection_requests,
    class_name: 'ConnectionRequest',
    foreign_key: :initiator_service_posting_id

  has_many :receiver_connection_requests,
    class_name: 'ConnectionRequest',
    foreign_key: :receiver_service_posting_id


  validates :summary, presence: true
  validates :summary, length: { maximum: 300 }

  validates :posting_type, presence: true
  validates :posting_type, inclusion: {in: ['Wanted', 'Available']}

  validates :service_type, presence: true
  validates :service_type, inclusion: {in: ServicePosting::ServiceTypes }

  validates :full_time_equivalents, presence: true
  validates :full_time_equivalents, numericality: {greater_than: 0, less_than_or_equal_to: 1}

  validates :description, length: { maximum: 50000 }



  def open_closed_text
    if self.closed then 'Closed' else 'Open' end
  end

  def seeking_summary
    "#{self.full_time_equivalents} FTE #{self.service_type}"
  end


  def full_matches

    query_posting_type = if self.posting_type == 'Wanted' then 'Available' else'Wanted' end

    time_operand = if self.posting_type == 'Available' then '<=' else '>=' end

    ServicePosting.where(
      closed: false,
      service_type: self.service_type,
      posting_type: query_posting_type)
    .where("full_time_equivalents #{time_operand} ?", self.full_time_equivalents)
    .where("id <> ?", self.id)
    .where("user_id <> ?", self.user.id)
    .order(full_time_equivalents: :desc)

  end

  def best_matches
    self.full_matches.limit(3)
  end


  before_validation do
    self.closed = false if self.closed.nil?
  end


end

app/controllers/service_postings_controller.rb
class ServicePostingsController < ApplicationController
  before_action :require_user_login

  before_action :set_service_posting, only: [:show, :edit, :update, :open, :close]
  before_action :require_ownership, only: [:edit, :update, :open, :close]

  layout "second_shift_pages"

  def show
  end

  def new
    @service_posting = ServicePosting.new
  end

  def edit
  end

  def create
    @service_posting = ServicePosting.new(service_posting_params)
    @service_posting.user = current_user

    if @service_posting.save
      redirect_to @service_posting, notice: 'Service posting was successfully created.'
    else
      render :new
    end
  end

  def update
    if @service_posting.update(service_posting_params)
      redirect_to @service_posting, notice: 'Service posting was successfully updated.'
    else
      render :edit
    end
  end


  ### Additional non-restful actions:

  def mine
    @service_postings = ServicePosting
      .where(user: current_user)
      .page(params[:page])
  end

  def available
    @service_postings = ServicePosting
      .where(closed: false, posting_type: 'Available')
      .page(params[:page])
  end

  def wanted
    @service_postings = ServicePosting
      .where(closed: false, posting_type: 'Wanted')
      .page(params[:page])
  end

  def search
  end


  def close
    @service_posting.closed = true
    @service_posting.save!
    redirect_to @service_posting, notice: 'The service posting was closed, and is no longer visible to the public.'
  end

  def open
    @service_posting.closed = false
    @service_posting.save!
    redirect_to @service_posting, notice: 'The service posting was re-opened, and is again visible to the public.'
  end



  private
    def set_service_posting
      @service_posting = ServicePosting.find(params[:id])
    end

    def service_posting_params
      params.require(:service_posting).permit(:posting_type, :summary, :description, :full_time_equivalents, :service_type)
    end

    def require_ownership
      if @service_posting.user != current_user
        flash[:notice] = 'You need to be the creator of the posting to do that.'
        redirect_to request.referer || @service_posting
      end
    end
end

app/views/service_postings/_connection_buttons.html.slim
/ receiver_service_posting is required.
/ initiator_service_posting is optional, since connections are permitted without matches.
- initiator_service_posting = initiator_service_posting || nil
- other_user = receiver_service_posting.user



/ If the users are connected:
- if Connection.connection_exists? current_user, other_user

  p
    = "You're connected. You can email #{other_user.name} at "
    = mail_to other_user.email


/ If there is an existing connection request, related to this one or not:
- elsif ConnectionRequest.current_connection_request current_user, other_user

  = render 'connection_requests/action_buttons', connection_request: ConnectionRequest.current_connection_request(current_user, other_user)


/ There is an old connection request which was accepted, but there is currently no connection. This means that the connection was removed at some point after being accepted. Offer a new connection button without summarizing the old request.
- elsif ConnectionRequest.old_connection_request(current_user, other_user)&.accepted?

  p = "You're not connected with #{other_user.name}."

  = form_with model: ConnectionRequest.new, method: :post, url: ss_connection_requests_path, local: true do |form|
    = form.hidden_field :initiator_service_posting_id, value: initiator_service_posting&.id
    = form.hidden_field :receiver_service_posting_id, value: receiver_service_posting.id
    = form.submit "Send request", class: "mui-btn mui-btn--primary"

/ If there is one or more old request:
- elsif ConnectionRequest.old_connection_request current_user, other_user

  p = "You're not connected with #{other_user.name}."

  / Since the old connection is resolved, the request action buttons will only render a little summary of how the last connection request turned out.
  = render 'connection_requests/action_buttons', connection_request: ConnectionRequest.old_connection_request(current_user, other_user)

  = form_with model: ConnectionRequest.new, method: :post, url: ss_connection_requests_path, local: true do |form|
    = form.hidden_field :initiator_service_posting_id, value: initiator_service_posting&.id
    = form.hidden_field :receiver_service_posting_id, value: receiver_service_posting.id
    = form.submit "Send request", class: "mui-btn mui-btn--primary"


/ If there is no connection or connection request:
- else

  = form_with model: ConnectionRequest.new, method: :post, url: ss_connection_requests_path, local: true do |form|
    = form.hidden_field :initiator_service_posting_id, value: initiator_service_posting&.id
    = form.hidden_field :receiver_service_posting_id, value: receiver_service_posting.id
    = form.submit "Send request", class: "mui-btn mui-btn--primary"


  / - elsif !service_posting.closed and !service_posting.connection_exists? match

app/views/service_postings/_form.html.slim
= form_with(model: service_posting, class: 'mui-form', local: true) do |form|

  - if service_posting.errors.any?
    .form-section#error-explanation
      h2 
        = "#{pluralize(service_posting.errors.count, "error")} prohibited this posting from being saved:"
      ul
        - service_posting.errors.full_messages.each do |message|
          li = message

  .form-section
    .mui-textfield
      = form.label :summary
      = form.text_field :summary
    
  .form-section
    .mui-textfield
      label Service available or wanted
    .mui-radio
      = form.radio_button :posting_type, 'Available'
      = form.label :posting_type_available, 'Available'
    .mui-radio
      = form.radio_button :posting_type, 'Wanted'
      = form.label :posting_type_wanted, 'Wanted'

  .form-section
    .mui-select
      = form.label :service_type
      = form.collection_select :service_type, ServicePosting::ServiceTypes, :to_s, :to_s, include_blank: true

  .form-section
    .mui-textfield
      = form.label :full_time_equivalents
      = form.number_field :full_time_equivalents, min: 0.1, max: 1, step: 0.1

  .form-section
    .mui-textfield
      = form.label :description
      = form.text_area :description







  .actions
    = form.submit class: 'mui-btn'

app/views/service_postings/_index_buttons.html.slim
.mui-row
  .mui-col-md-12.mui-col-xs-12
    = link_to 'View', service_posting_path(service_posting), class: 'mui-btn'

    - if service_posting.user == current_user

      = link_to 'Edit', edit_service_posting_path(service_posting), class: 'mui-btn'

app/views/service_postings/_info.html.slim
.mui-row
  .mui-col-md-12.mui-col-xs-12
    h2.bottom-border = service_posting.summary

.mui-row
  .mui-col-md-10.mui-col-xs-12
    p
      strong By: 
      = service_posting.user.name
      - if service_posting.user == current_user
        strong = " (You)"
  .mui-col-md-2.mui-col-xs-12
    p = service_posting.open_closed_text


.mui-row
  .mui-col-md-12.mui-col-xs-12
    p
      strong 
        = service_posting.posting_type
        | : 
      = service_posting.seeking_summary

.mui-row
  .mui-col-md-12.mui-col-xs-12
    p
      strong Description: 
      = service_posting.description


- if service_posting.user == current_user
  - if matches.any?
    .mui-row
      .mui-col-md-12.mui-col-xs-12
        h3 Suggested Matches

    - matches.each_slice 3 do |matches_slice|
      .mui-row
        - matches_slice.each do |match|
          .mui-col-md-4.mui-col-xs-12
            h2.bottom-border = match.summary
            p
              strong By: 
              = match.user.name
            p 
              strong = "#{match.posting_type}: "
              = match.seeking_summary
              = link_to 'More Info', service_posting_path(match), class: 'mui-btn'

            - if show_connection_buttons
              h3 Connection Info
              = render 'service_postings/match_connection_buttons', initiator_service_posting: service_posting, receiver_service_posting: match


    / For spacing
    .mui-row.form-section

  - else
    .mui-row.form-section
      .mui-col-md-12.mui-col-xs-12
        p
          em No suggested matches found

app/views/service_postings/_match_connection_buttons.html.slim
/ receiver_service_posting is required.
/ initiator_service_posting is optional, since connections are permitted without matches.
- initiator_service_posting = initiator_service_posting || nil
- other_user = receiver_service_posting.user


/ If it's you, no-op
- if current_user == other_user


/ If the users are connected:
- elsif Connection.connection_exists? current_user, other_user

  h3 Connection
  p = "You're connected with #{other_user.name}"
  = render 'users/contact_info', user: other_user



/ If there is an existing connection request, related to this one or not:
- elsif ConnectionRequest.current_connection_request current_user, other_user

  = render 'connection_requests/action_buttons', connection_request: ConnectionRequest.current_connection_request(current_user, other_user)


/ There is an old connection request which was accepted, but there is currently no connection. This means that the connection was removed at some point after being accepted. Offer a new connection button without summarizing the old request.
- elsif ConnectionRequest.old_connection_request(current_user, other_user)&.accepted?

  p = "You're not connected with #{other_user.name}."

  = form_with model: ConnectionRequest.new, url: ss_connection_requests_path do |form|
    = form.hidden_field :initiator_service_posting_id, value: initiator_service_posting&.id
    = form.hidden_field :receiver_service_posting_id, value: receiver_service_posting.id
    = form.submit "Send request", class: "mui-btn"

/ If there is one or more old request:
- elsif ConnectionRequest.old_connection_request current_user, other_user

  p = "You're not connected with #{other_user.name}."

  / Since the old connection is resolved, the request action buttons will only render a little summary of how the last connection request turned out.
  = render 'connection_requests/action_buttons', connection_request: ConnectionRequest.old_connection_request(current_user, other_user)

  = form_with model: ConnectionRequest.new, url: ss_connection_requests_path do |form|
    = form.hidden_field :initiator_service_posting_id, value: initiator_service_posting&.id
    = form.hidden_field :receiver_service_posting_id, value: receiver_service_posting.id
    = form.submit "Send request", class: "mui-btn"


/ If there is no connection or connection request:
- else

  = form_with model: ConnectionRequest.new, url: ss_connection_requests_path do |form|
    = form.hidden_field :initiator_service_posting_id, value: initiator_service_posting&.id
    = form.hidden_field :receiver_service_posting_id, value: receiver_service_posting.id
    = form.submit "Send request", class: "mui-btn"

app/views/service_postings/_owner_buttons.html.slim
.mui-row
  .mui-col-md-12.mui-col-xs-12
    - if service_posting.user == current_user

      - if service_posting.closed == true
        = form_with url: open_service_posting_path(service_posting) do |form|
          = form.submit "Re-open", class: "mui-btn"

      - else
        = form_with url: close_service_posting_path(service_posting), class: 'mui-form--inline' do |form|
          / The 'edit' link has nothing to do with the form, but it needs to be nested in the form tag to display inline with this submit button.
          = link_to 'Edit', edit_service_posting_path(service_posting), class: 'mui-btn'
          = form.submit "Close", class: "mui-btn"

app/views/service_postings/available.html.slim
.mui-container
  .mui-row
    .mui-col-md-12.mui-col-xs-12
      h2 Browse Available Postings

      - if @service_postings.empty?
        em There are no postings to show.

- @service_postings.each do |service_posting|
  .mui-container
    = render 'service_postings/info', service_posting: service_posting, show_connection_buttons: false, matches: service_posting.best_matches
    = render 'service_postings/index_buttons', service_posting: service_posting

.form-section
= paginate @service_postings

app/views/service_postings/edit.html.slim
h2 Edit Service Posting

= render 'form', service_posting: @service_posting


= link_to 'Cancel', @service_posting, class: 'mui-btn'

app/views/service_postings/mine.html.slim
.mui-container
  .mui-row
    .mui-col-md-12.mui-col-xs-12
      h2 My Postings

      - if @service_postings.empty?
        em There are no postings to show.

- @service_postings.each do |service_posting|
  .mui-container
    = render 'service_postings/info', service_posting: service_posting, show_connection_buttons: false, matches: service_posting.best_matches
    = render 'service_postings/index_buttons', service_posting: service_posting

.form-section
= paginate @service_postings

app/views/service_postings/new.html.slim
h2 Create a Service Posting

= render 'form', service_posting: @service_posting

app/views/service_postings/search.html.slim
h2 postings/search

app/views/service_postings/show.html.slim
.mui-container
  = render 'service_postings/info', service_posting: @service_posting, show_connection_buttons: true, matches: @service_posting.full_matches
  = render 'service_postings/owner_buttons', service_posting: @service_posting
  = render 'service_postings/match_connection_buttons', receiver_service_posting: @service_posting

app/views/service_postings/wanted.html.slim
.mui-container
  .mui-row
    .mui-col-md-12.mui-col-xs-12
      h2 Browse Wanted Postings

      - if @service_postings.empty?
        em There are no postings to show.

- @service_postings.each do |service_posting|
  .mui-container
    = render 'service_postings/info', service_posting: service_posting, show_connection_buttons: false, matches: service_posting.best_matches
    = render 'service_postings/index_buttons', service_posting: service_posting

.form-section
= paginate @service_postings